ahoyapi: v2
commands:

  up:
    usage: Start the docker containers.
    cmd: |
      if [ ! -d "data/db/mysql" ]; then
        mkdir -p data/db/mysql
      fi
      if [ -f "docker-compose.override" ] && [ ! -f "docker-compose.override.yml" ]; then
        cp docker-compose.override docker-compose.override.yml
      fi
      if [ -f "docker-compose.local.yml" ]; then
        rm -rf docker-compose.override.yml
        docker-compose -f docker-compose.local.yml up -d
      else
        docker-compose up -d
      fi
  down:
    usage: Stop the docker containers.
    cmd: |
      docker-compose down

  logs:
    usage: Check the docker container logs.
    cmd: |
      docker-compose logs -f

  drup:
    usage: Install clean drupal website.
    cmd: |
      vendor/bin/robo drup
