ahoyapi: v2
commands:

  up:
    usage: Start the docker containers.
    cmd: |
      if [ ! -d "data/db/mysql" ]; then
        mkdir -p data/db/mysql
      fi
      if [ -f "docker-compose.override" ] && [ ! -f "docker-compose.override.yml" ]; then
        cp docker-compose.override docker-compose.override.yml
      fi
      if [ -f "docker-compose.local.yml" ]; then
        rm -rf docker-compose.override.yml
        docker-compose -f docker-compose.local.yml up -d
      else
        docker-compose up -d
      fi
  down:
    usage: Stop the docker containers.
    cmd: |
      docker-compose down

  logs:
    usage: Check the docker container logs.
    cmd: |
      docker-compose logs -f

  composer:
    usage: Run a Composer command.
    cmd: |
      ahoy runphp composer $@

  dre:
    usage: Reinstall module.
    cmd:
      ahoy drush pmu $1 && ahoy drush en $1

  drush:
    usage: Run a Drush command.
    cmd: |
      . .env
      ahoy runphp vendor/bin/drush --uri=$DRUPAL_BASE_URL $@


  sh:
    usage: Start a shell on the web container.
    cmd: |
      ahoy runphp bash

  install:
    usage: Install clean drupal website
    cmd: |
      ahoy drush si 


  runcmd:
    usage: Run a command in a ephemeral php container.
    cmd: |
      docker run --rm -i -v $(pwd):/var/www/html fpfis/httpd-php-dev:7.4 $@

  runphp:
    usage: Run a command inside a running php container.
    cmd: |
      if [ -f "docker-compose.local.yml" ]; then
        docker-compose -f docker-compose.local.yml exec web $@
      else
        docker-compose exec web $@
      fi

  behat:
    usage: Run behat tests.
    cmd: |
      ahoy runner toolkit:test-behat


  phpcs:
    usage: Run phpcs.
    cmd: |
      ahoy runner toolkit:test-phpcs


  cr:
    usage: Runs drush cache rebuild.
    cmd: |
      ahoy drush cr
