services:
  web:
    image: registry.fpfis.eu/digit/devsecops/httpd-php:8.3-dev
    working_dir: ${PWD}
    ports:
      - 80:80
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
      # - ./custom.ini:/etc/php/8.1/fpm/conf.d/custom.ini
      # - ./wwwcustom.conf:/etc/php/8.1/fpm/pool.d/wwwcustom.conf
      # - ~/.bashrc:/root/.bashrc
      # - ~/.gitconfig:/root/.gitconfig
      # - ~/.ssh:/root/.ssh:ro
    environment:
      DOCUMENT_ROOT: ${PWD}/web
      HTTP_PORT: 80
      # XDEBUG CONFIGURATION
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=10.254.254.254 client_port=9003 start_with_request=yes"
      XDEBUG_SESSION: Docker
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
  mysql:
    image: percona/percona-server:8.0
    command: --max_allowed_packet=1073741824
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8081:80
      volumes:
        - /sessions

volumes:
  mysql:
