version: "2"
services:
  web:
    image: fpfis/httpd-php-dev:7.3
    working_dir: ${PWD}
    ports:
      - 80:80
    volumes:
      - ${PWD}:${PWD} # Non Mac users.
      - ./custom.ini:/etc/php/7.3/fpm/conf.d/custom.ini
      - ./custom.conf:/etc/apache2/conf.d/custom.conf
      - ./wwwcustom.conf:/etc/php/7.3/fpm/pool.d/wwwcustom.conf
      - ./rmconfdup.sh:/root/rmconfdup.sh
      - ~/.bashrc:/root/.bashrc
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh:ro
      # if you need to enable mailhog and mhsendmail use these settings
      #- ${PWD}/dev/mhsendmail:/usr/local/bin/mhsendmail
      #- ${PWD}/dev/mailhog.ini:/etc/php/7.3/cli/conf.d/mailhog.ini
      #- ${PWD}/dev/mailhog.ini:/etc/php/7.3/fpm/conf.d/mailhog.ini
      # - nfsmount:/var/www/html # Mac Users with the nfsmount volume.
    environment:
      DOCUMENT_ROOT: ${PWD}/web
      HTTP_PORT: 80
      # ASDA CREDENTIALS
      # By leaving these variables empty Docker Compose will set them to their host values.
      ASDA_USER:
      ASDA_PASSWORD:
      # XDEBUG CONFIGURATION
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=10.254.254.254 client_port=9003 start_with_request=yes"
      XDEBUG_SESSION: Docker
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1
    env_file:
      - .env
  mysql:
    image: percona/percona-server:5.7
    command: --max_allowed_packet=1073741824
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
        - 8081:80
      volumes:
        - /sessions

volumes:
  mysql:
